### ISSUE TITLE
For Rails 4.1.6, need to update tzinfo from 0.3.22 to 1.2.2+

### ISSUE THREAD

**Issue by ACPK** [envoy/eventbrite#1]
Bundler could not find compatible versions for gem "tzinfo":
  In Gemfile:
    eventbrite (>= 0) ruby depends on
      tzinfo (~> 0.3.22) ruby

```
rails (= 4.1.6) ruby depends on
  activesupport (= 4.1.6) ruby depends on
    tzinfo (1.2.2)
```

**Comment by drhanlau** [comment]
Hi, have you found a solution for that? Facing the same problem here too :(

**Comment by kamal** [comment]
I'm unable to reproduce this issue. The gem itself doesn't have a dependency on tzinfo. You can test this out by doing a `bundle install` in this repo and inspecting the `Gemfile.lock`.
