### ISSUE TITLE
Querying nested parameters

### ISSUE THREAD

**Issue by lasernite** [envoy/eventbrite#13]
I don't see anything in the docs so was wondering if it's possible with the gem to make queries in which the params have nested names like 'location.latitude' or 'location.longitude'?

Currently getting error:

There are errors with your arguments: location[latitude] - Unknown parameter, location[within] - Unknown parameter, location[longitude] - Unknown parameter

Can't seem to just pass something 'location.longitude' as a string or variable form either.

Any suggestions?

Thanks!

**Comment by lasernite** [comment]
For reference: https://www.eventbrite.com/developer/v3/endpoints/events/

**Comment by sssionggg** [comment]
what is your code for the query?

**Comment by lasernite** [comment]
Eventbrite::Event.search({popular: true, location: {latitude: @geo_location.latitude.to_s, longitude: @geo_location.longitude.to_s, within: "10km"} })

**Comment by sssionggg** [comment]
@lasernite can you try this:

``` ruby
Eventbrite::Event.search({popular: true, "location.latitude": @geo_location.latitude.to_s, "location.longitude": @geo_location.longitude.to_s, "location.within": "10km"})
```

**Comment by lasernite** [comment]
Yep, that's what I initially tried, but it gives syntax errors. I haven't been able to successfully pass any string as a key, which is what I meant by "Can't seem to just pass something 'location.longitude' as a string or variable form either." above.

`/Users/lasernite/rails_projects/elvent/app/controllers/welcome_controller.rb:104: syntax error, unexpected ':', expecting => ...lar: true, "location.latitude": @geo_location.latitude.to_s,... ... ^ /Users/lasernite/rails_projects/elvent/app/controllers/welcome_controller.rb:104: syntax error, unexpected ':', expecting :: or '[' or '.' ...ude.to_s, "location.longitude": @geo_location.longitude.to_s... ... ^ /Users/lasernite/rails_projects/elvent/app/controllers/welcome_controller.rb:104: syntax error, unexpected ':', expecting :: or '[' or '.' ...gitude.to_s, "location.within": "10km"}) ... ^ /Users/lasernite/rails_projects/elvent/app/controllers/welcome_controller.rb:104: syntax error, unexpected '}', expecting keyword_end ...o_s, "location.within": "10km"}) ... ^`

**Comment by sssionggg** [comment]
what ruby version are you using?  that syntax should be valid.

**Comment by sssionggg** [comment]
@lasernite i just tried it out in ruby version `2.2.3`.  it works.

**Comment by sssionggg** [comment]
if you want to stick with the ruby version that you are using, try this: 

``` ruby
Eventbrite::Event.search({popular: true, :"location.latitude" => @geo_location.latitude.to_s, :"location.longitude" => @geo_location.longitude.to_s, :"location.within" => "10km"})
```

**Comment by lasernite** [comment]
Fantastic, thanks :)
