### ISSUE TITLE
TicketClass resource

### ISSUE THREAD

**Issue by jeffblake** [envoy/eventbrite#14]
It would be great if Eventbrite::TicketClass was implemented.

https://www.eventbrite.com/developer/v3/formats/event/#ebapi-std:format-ticket_class

**Comment by Kosai106** [comment]
Yeah, it's quite annoying not being able to get ticket data too.

No promises, but I'll try to see if I can implement this feature myself somehow.

**Comment by Kosai106** [comment]
It took me 3 months to get around to it, but here we are.

**Comment by kamal** [comment]
Fixed in #25
