### ISSUE TITLE
Allow expansions on .retrieve

### ISSUE THREAD

**Issue by bsgreenb** [envoy/eventbrite#5]
Expansions let you retrieve extra stuff.  You can provide expansions on `.all` currently via `params` parameter, but not on `.retrieve`.  Here's an example of an Attendee retrieve with an expansion:

https://www.eventbriteapi.com/v3/events/17192710861/attendees/541119287/?token=6W6MK2IRTGDVSXQM3MNY&expand=promotional_code

Simple solution would be to let us pass in params to `.retrieve`.

**Comment by bsgreenb** [comment]
In the meantime, I forked the repo at http://github.com/bsgreenb/eventbrite with a hacky patch that adds `?expand=promotional_code` to `Attendee.url`

**Comment by sssionggg** [comment]
@bsgreenb you should be able to do the same with retrieve too, have you tried this?

``` ruby
Eventbrite::Attendee.retrieve('event_id', id: 'attendee_id', expand: 'promotional_code')
```

Also, you might not want to expose the token you have from the example you provided.

**Comment by sssionggg** [comment]
i just tried it out and my example above works flawlessly.  so, i am closing this issue.

just remember this, `expand` is just one example here, it supports other arguments too.

**Comment by bsgreenb** [comment]
@siong1987 Awesome, was a mistake on my part.  Going to un-fork.  BTW check out the Access Codes-base promo dashboard I'm building @ bsgreenb/promo-dashboard

**Comment by sssionggg** [comment]
@bsgreenb lol.  looking at my comment now, it seems like my comment looks a bit harsh.  note to myself: never try to work on anything after 2am midnight.  haha.

also, i should have made it clear in the examples too.
